version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    image: node:14
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: ["node", "index.js"]
    ports:
      - "3000:3000"
