name: linting
on:
  workflow_dispatch:
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: List all Files
        run: ls
      - name: Ansible Linting
        uses: ansible/ansible-lint@main
  docker-compose-lint:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: docker compose lint
        uses: sjafferali/docker-compose-lint-action@v0.1.2
        with:
          compose-file: './Docker/docker-compose.yaml'
  docker-compose-lint-with-image:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: docker compose lint
        run:  docker run -t --rm -v ${{ github.workspace }}:/app zavoloklom/dclint /app/Docker/docker-compose.yaml
