
name: prom-data-backup
on:
  workflow_dispatch:
jobs:
  prom-data-backup:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: docker compose 
        run: |
          cd Docker
          ls
          docker-compose -f ./Docker/docker-compose.yaml up
      - name: list all docker containers
        run: docker ps -a
        
