name: prom-data-backup

on: push
jobs:
  prom-data-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          # Install Docker Compose
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: |
          cd Docker
          ls
          docker-compose -f ./docker-compose.yaml up -d
          sleep 60  # Wait 60 seconds to ensure Prometheus starts and scrapes data

      - name: List all Docker containers
        run: |
          docker ps -a

      - name: Copy Prometheus Data from Container
        run: |
          # Get the current date for backup naming
          BACKUP_DIR="/backup/prom-$(date +'%Y-%m-%d')"
          sudo mkdir -p $BACKUP_DIR  # Create the folder if it doesn't exist
          
          # Copy data directly from the container's volume
          sudo docker cp prometheus:/prometheus/. $BACKUP_DIR/
          echo "Prometheus data has been backed up to: $BACKUP_DIR"

      - name: List all backup files
        run: |
          ls /backup/prom-$(date +'%Y-%m-%d')
