name: prom-data-backup
on: push

jobs:
  prom-data-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Compose
        run: |
          # Install Docker Compose
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: |
          cd Docker
          ls
          docker-compose -f ./docker-compose.yaml up -d
          sleep 100
          
      - name: List all Docker containers
        run: |
          docker ps -a
          sudo cp Docker/docker-compose.yaml Docker/prometheus_data/


      - name: list all prometheus data
        run: | 
          cd Docker/prometheus_data/
          ls
